[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = '''
  nnoremap [denite] <Nop>
  nmap <C-u>  [denite]
  nmap <silent> [denite]f :<C-u>Denite file/rec<CR>
'''
hook_post_source = '''
  if executable('rg')
    call denite#custom#var('file/rec', 'command',
          \ [ 'rg', '--files', '--follow', '--hidden', '--glob', '!.git' ])
  endif
  call denite#custom#map('insert', '<Esc>', '<denite:enter_mode:normal>', 'noremap')
  call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>', 'noremap')
  call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>', 'noremap')
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
depends = [ 'vimproc.vim' ]
on_cmd = 'QuickRun'
hook_add = '''
  nnoremap [Space]r :cclose<CR>:write<CR>:QuickRun -mode n<CR>
  vnoremap [Space]r :QuickRun -mode n<CR>
'''
hook_source = '''
  let g:quickrun_config = {
        \ '_': {
        \   'runner': 'vimproc',
        \   'runner/vimproc/updatetime': 100,
        \   'outputter': 'error',
        \   'outputter/error/success': 'buffer',
        \   'outputter/error/error': 'quickfix',
        \   'outputter/buffer/split': ':botright 8sp',
        \ },
        \ }
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'junegunn/vim-easy-align'
on_cmd = 'EasyAlign'
hook_add = '''
vnoremap <silent> <Enter> :EasyAlign<cr>
'''

[[plugins]]
repo = 'itchyny/vim-cursorword'

[[plugins]]
repo = 'rhysd/accelerated-jk'
on_map = {n = '<Plug>'}
hook_add = '''
  nmap <silent>j <Plug>(accelerated_jk_gj)
  nmap <silent>k <Plug>(accelerated_jk_gk)
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_path = '.*'
